ruboty:
  build: .
  links:
    - redis
  command: ruboty --dotenv --load ./lib/ruboty/trello_reporter.rb
redis:
  image: hypriot/rpi-redis
  ports:
    - 6379:6379
  volumes:
    - /srv/docker/redis:/var/lib/redis
  restart: always
